app/models.py
from app import db
import datetime
from flask_login import UserMixin
from sqlalchemy import DateTime
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import relationship
from typing import List


class Person(db.Model):
    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return str(self.id)

    __tablename__ = "person_table"

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))
    username = db.Column(db.String(100), unique=True)
    todolist: Mapped[List["TodoList"]] = relationship(back_populates="person")

    def __repr__(self):
        return f'<Person {self.username}>'


class TodoList(db.Model):
    __tablename__ = "todolist_table"
    id = db.Column(db.Integer, primary_key=True)

    category = db.Column(db.String(1000))
    description = db.Column(db.String(10000))
    status = db.Column(db.String(100))
    created_date = db.Column(DateTime, default=datetime.datetime.utcnow)
    person_id: Mapped[int] = mapped_column(ForeignKey("person_table.id"))
    person: Mapped["Person"] = relationship(
        back_populates="todolist", single_parent=True)

app/main/forms.py
from flask_wtf import Form
from wtforms.csrf.session import SessionCSRF
from wtforms import validators, ValidationError
from wtforms import StringField, SubmitField, PasswordField, BooleanField, TextAreaField, SelectField, HiddenField
from wtforms.validators import DataRequired, EqualTo


class MyBaseForm(Form):
    class Meta:
        csrf = True
        csrf_class = SessionCSRF
        csrf_secret = b'EPejf00jpfj8Gx1SjnyLxwBEDQfnQ9DJYe0Ym'


class AddTask(MyBaseForm):
    category = StringField("Category", validators=[DataRequired()])
    description = TextAreaField("Description", validators=[DataRequired()])
    submit = SubmitField("Save")


class EditTask(MyBaseForm):
    category = StringField("Category", validators=[DataRequired()])
    description = TextAreaField("Description", validators=[DataRequired()])
    status = SelectField("Status", choices=['Pending', 'Done'])
    submit = SubmitField("Save")


class DeleteTask(MyBaseForm):
    delete_task_id = HiddenField()
    submit = SubmitField("Delete")

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import UserMixin, LoginManager
from sqlalchemy import event
import sqlite3
db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()
login_manager.login_view = 'auth.login'


def create_app(config_class=Config):

    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)

    login_manager.init_app(app)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)
    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from app.main import bp
from flask import render_template, request, session, redirect, url_for
from flask_login import login_required, current_user
from app.main.forms import AddTask, EditTask, DeleteTask
from app.models import TodoList, Person
from app import db


@bp.route('/')
def index():
    return render_template('index.html')


@bp.route('/profile')
@login_required
def profile():
    person = Person.query.filter_by(username=current_user.username).first()
    personTodo = person.todolist
    return render_template('profile.html', todolist=personTodo)


# Profile_edit PLUS delete hidden form
@bp.route('/profile_edit', methods=('GET', 'POST'))
@login_required
def profile_edit():
    # With Delete inside since tackle this alone would make no sense
    form = DeleteTask(request.form, meta={'csrf_context': session})
    if request.method == "POST" and form.validate():
        db.session.delete(TodoList.query.get(
            int(request.form['delete_task_id'])))
        db.session.commit()
        # take this line carefully
        return redirect(url_for('main.profile_edit'))
    person = Person.query.filter_by(username=current_user.username).first()
    personTodo = person.todolist
    return render_template('profile_edit.html', todolist=personTodo, form=form)

# Adding new task
@bp.route('/profile_add2DoList', methods=('GET', 'POST'))
@login_required
def profile_add2DoList():
    form = AddTask(request.form, meta={'csrf_context': session})
    if request.method == "POST" and form.validate():
        person = Person.query.filter_by(username=current_user.username).first()
        newTask = TodoList(
            category=request.form['category'],
            description=request.form['description'],
            status="Pending",
            person=person
        )
        db.session.add(newTask)
        db.session.commit()
        return redirect(url_for('main.profile_edit'))
    return render_template('profile_add2DoList.html', form=form)

# Task editing here
@bp.route('/profile_edit2DoList/<int:task_id>', methods=('GET', 'POST'))
@login_required
def profile_edit2DoList(task_id):
    form = EditTask(request.form, meta={'csrf_context': session})

    if request.method == "POST" and form.validate():
        task2Edit = TodoList.query.get(task_id)

        # Reassign again the value of task
        task2Edit.category = request.form['category']
        task2Edit.description = request.form['description']
        task2Edit.status = request.form['status']

        # Save them up to db
        db.session.add(task2Edit)
        db.session.commit()
        return redirect(url_for('main.profile_edit'))
    task2Render = TodoList.query.get(task_id)
    return render_template(
        'profile_edit2DoList.html',
        task=task2Render,
        defaultDescription='this.innerHTML="'+task2Render.description +'"',
        form=form)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
        <link rel="shortcut icon" href="todost.png">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
        <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'>
        <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.4.0/animate.min.css'>
        <link rel='stylesheet prefetch' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css'>
        <link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">
        <title>Document</title>
        <style>
                .alert {
                        padding: 20px;
                        margin: 5px;
                        color: #970020;
                        background-color: #ffd5de;
                }
        </style>
</head>
<body>
        <ul class="nav justify-content-center">
                {% if not current_user.is_authenticated %}
                <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ url_for('main.index')}}">Home</a>
                </li>
                <li class="nav-item">
                        <a class="nav-link" href="#">Todo-Tracker</a>
                </li>
                <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                </li>
                <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}" tabindex="-1">Login</a>
                </li>
                {% endif %}

                {% if current_user.is_authenticated %}
                  <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ url_for('main.profile')}}">Home</a>
                </li>
                <li class="nav-item">
                        <a class="nav-link" href="#">Todo-Tracker</a>
                </li>
                <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}" tabindex="-1">Log Out</a>
                </li>
                {% endif %}

        </ul>
        {% block content %}
        {% endblock %}
       
</body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block content %}
        <div class="container">
         <svg class="mx-auto d-block bg-020631" width="100px" height="100px" viewBox="0 0 100 100" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
            <desc>Created with Sketch.</desc>
            <defs>
               <linearGradient x1="34.9523037%" y1="0%" x2="116.039609%" y2="115.484477%" id="linearGradient-1">
                  <stop stop-color="#1700FF" offset="0%"></stop>
                  <stop stop-color="#B10EF1" offset="100%"></stop>
               </linearGradient>
               <rect id="path-2" x="19.8783454" y="5.46149939" width="67.2578578" height="67.2008596" rx="8.99999976"></rect>
               <filter x="-35.7%" y="-28.3%" width="162.4%" height="162.5%" filterUnits="objectBoundingBox" id="filter-3">
                  <feOffset dx="-3" dy="2" in="SourceAlpha" result="shadowOffsetOuter1"></feOffset>
                  <feGaussianBlur stdDeviation="6.5" in="shadowOffsetOuter1" result="shadowBlurOuter1"></feGaussianBlur>
                  <feColorMatrix values="0 0 0 0 0.0296505968   0 0 0 0 0.0172602666   0 0 0 0 0.100446429  0 0 0 0.423177083 0" type="matrix" in="shadowBlurOuter1"></feColorMatrix>
               </filter>
               <linearGradient x1="0%" y1="0%" x2="115.291753%" y2="112.548614%" id="linearGradient-4">
                  <stop stop-color="#1700FF" offset="0%"></stop>
                  <stop stop-color="#9E0CF3" offset="83.2001616%"></stop>
                  <stop stop-color="#B10EF1" offset="100%"></stop>
               </linearGradient>
               <path d="M40.2086259,6.21042694 C39.2480415,5.24152695 38.1027468,4.75708888 36.7727039,4.75708888 C35.4426658,4.75708888 34.3096854,5.24152695 33.3737297,6.21042694 L16.3049725,23.7622477 L12.0193093,19.3649757 C11.0833536,18.3960804 9.9503732,17.9116376 8.62033507,17.9116376 C7.29029269,17.9116376 6.14499751,18.3960804 5.1844131,19.3649757 C4.24845898,20.3338709 3.78048896,21.5077058 3.78048896,22.8865186 C3.78048896,24.2653314 4.24845898,25.4391663 5.1844131,26.4080615 L12.8690505,34.3082476 C13.8296349,35.2771428 14.9749296,35.7615833 16.3049725,35.7615833 C17.6350106,35.7615833 18.767991,35.2771428 19.7039467,34.3082476 L40.2086259,13.2535128 C41.1445816,12.2597758 41.61255,11.0797257 41.61255,9.71333379 C41.61255,8.34694665 41.1445816,7.17932216 40.2086259,6.21042694 Z" id="path-5"></path>
               <filter x="-51.5%" y="-62.9%" width="203.1%" height="225.8%" filterUnits="objectBoundingBox" id="filter-6">
                  <feOffset dx="0" dy="0" in="SourceAlpha" result="shadowOffsetOuter1"></feOffset>
                  <feGaussianBlur stdDeviation="6.5" in="shadowOffsetOuter1" result="shadowBlurOuter1"></feGaussianBlur>
                  <feColorMatrix values="0 0 0 0 1   0 0 0 0 1   0 0 0 0 1  0 0 0 0.588937953 0" type="matrix" in="shadowBlurOuter1"></feColorMatrix>
               </filter>
            </defs>
            <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
               <g id="Artboard-2" transform="translate(-214.000000, -272.000000)">
                  <g id="Group-4" transform="translate(201.000000, 269.000000)">
                     <g id="Group-3" transform="translate(58.787474, 58.534712) rotate(-6.000000) translate(-58.787474, -58.534712) translate(5.642436, 5.434712)">
                        <g id="Group-2" transform="translate(52.899385, 53.035097) rotate(7.000000) translate(-52.899385, -53.035097) translate(5.609309, 5.785097)">
                           <path d="M20.0219734,15.1240886 L74.1829282,14.1930575 C79.1527566,14.1076258 83.2508546,18.0672116 83.3362864,23.03704 C83.3371726,23.0885978 83.3376158,23.1401624 83.3376158,23.1917278 L83.3376158,72.0429044 C83.3376158,76.9531616 79.4018358,80.9571794 74.4923039,81.0415747 L20.3313491,81.9726057 C15.3615207,82.0580374 11.2634227,78.0984516 11.1779909,73.1286232 C11.1771047,73.0770654 11.1766615,73.0255009 11.1766615,72.9739354 L11.1766615,24.1227589 C11.1766615,19.2125016 15.1124415,15.2084838 20.0219734,15.1240886 Z" id="Rectangle" fill="url(#linearGradient-1)" transform="translate(47.257139, 48.082832) scale(-1, -1) rotate(-25.000000) translate(-47.257139, -48.082832) "></path>
                           <g id="Rectangle" transform="translate(53.507274, 39.061929) rotate(-10.000000) translate(-53.507274, -39.061929) ">
                              <use fill="black" fill-opacity="1" filter="url(#filter-3)" xlink:href="#path-2"></use>
                              <use fill="#FBFBFB" fill-rule="evenodd" xlink:href="#path-2"></use>
                           </g>
                        </g>
                     </g>
                     <g id="Group-5" transform="translate(43.000000, 26.000000)">
                        <path d="M41.1093892,10.5623533 C40.1488048,9.59345333 39.0035101,9.10901526 37.6734673,9.10901526 C36.3434291,9.10901526 35.2104488,9.59345333 34.274493,10.5623533 L17.2057358,28.1141741 L12.9200727,23.716902 C11.9841169,22.7480068 10.8511366,22.263564 9.52109843,22.263564 C8.19105605,22.263564 7.04576086,22.7480068 6.08517646,23.716902 C5.14922234,24.6857973 4.68125232,25.8596322 4.68125232,27.238445 C4.68125232,28.6172578 5.14922234,29.7910927 6.08517646,30.7599879 L13.7698139,38.660174 C14.7303983,39.6290692 15.875693,40.1135096 17.2057358,40.1135096 C18.535774,40.1135096 19.6687543,39.6290692 20.6047101,38.660174 L41.1093892,17.6054392 C42.045345,16.6117022 42.5133134,15.4316521 42.5133134,14.0652602 C42.5133134,12.698873 42.045345,11.5312485 41.1093892,10.5623533 Z" id="Page-1" fill="url(#linearGradient-4)" opacity="0.3" transform="translate(23.597283, 24.611262) rotate(-16.000000) translate(-23.597283, -24.611262) "></path>
                        <path d="M42.0101526,14.2623533 C41.0495682,13.2934533 39.9042735,12.8090153 38.5742306,12.8090153 C37.2441925,12.8090153 36.1112121,13.2934533 35.1752564,14.2623533 L18.1064992,31.8141741 L13.820836,27.416902 C12.8848803,26.4480068 11.7518999,25.963564 10.4218618,25.963564 C9.09181941,25.963564 7.94652422,26.4480068 6.98593982,27.416902 C6.78271177,27.6272827 6.60154798,27.8473258 6.4424483,28.0770317 C5.8688243,28.9052219 5.58201568,29.8590202 5.58201568,30.938445 C5.58201568,32.3172578 6.04998569,33.4910927 6.98593982,34.4599879 L14.6705772,42.360174 C15.6311616,43.3290692 16.7764563,43.8135096 18.1064992,43.8135096 C19.4365373,43.8135096 20.5695177,43.3290692 21.5054734,42.360174 L42.0101526,21.3054392 C42.9461083,20.3117022 43.4140767,19.1316521 43.4140767,17.7652602 C43.4140767,16.398873 42.9461083,15.2312485 42.0101526,14.2623533 Z" id="Page-1" fill="url(#linearGradient-4)" opacity="0.2" transform="translate(24.498046, 28.311262) rotate(-16.000000) translate(-24.498046, -28.311262) "></path>
                        <g id="Page-1" transform="translate(22.696519, 20.259336) rotate(-16.000000) translate(-22.696519, -20.259336) ">
                           <use fill="black" fill-opacity="1" filter="url(#filter-6)" xlink:href="#path-5"></use>
                           <use fill="url(#linearGradient-4)" fill-rule="evenodd" xlink:href="#path-5"></use>
                        </g>
                     </g>
                  </g>
               </g>
            </g>
         </svg>
                <div class="align-self-center mx-auto custom-button">
                        <a role="button"  href="{{ url_for('auth.register') }}"class="btn btn-primary btn-lg login mt-3">Let's go right into it 🖖</a>
                </div>


         </div>
        {% endblock %}
        

app/templates/profile.html
{% extends "base.html" %}

{% block content %}
<section class="vh-100">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card rounded-3">
          <div class="card-body p-4">


              <div class="col-12 d-flex text-center align-items-center">
                <h4 class="mr-3">To Do App</h4>
                <a role="button" href="{{ url_for('main.profile_edit') }}" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary">Modify</a>
              </div>

            <table class="table mb-4">
              <thead>
               
                <tr>
                  <th scope="col">Category</th>
                  <th scope="col">Description</th>
                  <th scope="col">Status</th>
                  <th scope="col">Date Created</th>
                </tr>
              </thead>
              <tbody>
                {% for todo in todolist %}
                  <tr>
                    <td>{{ todo.category }}</td>
                    <td>{{ todo.description }}</td>
                    <td>{{ todo.status }}</td>
                    <td>{{ todo.created_date.strftime("%b, %d %Y")}}</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

app/templates/profile_add2DoList.html
{% extends "base.html" %}

{% block content %}
        <section class="vh-100">
        <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-9 col-xl-7">
                <div class="card rounded-3">
                <div class="card-body p-4">
                        <form class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2" method="POST">
                                {{ form.csrf_token() }}
                                <div class="col-12" style="padding-top: 2em;">
                                        <div data-mdb-input-init class="form-outline mb-4 d-block align-items-center">
                                                {{ form.category.label(class="form-label mr-3") }}
                                                {{ form.category(class="form-control") }}
                                        </div>
                                        <div data-mdb-input-init class="form-outline mb-4 d-block align-items-center">
                                                {{ form.description.label(class="form-label mr-3") }}
                                                {{ form.description(class="form-control") }}
                                        </div>
                                </div>
                                <div class="d-flex flex-row col-12">
                                        {{ form.submit(class="mr-3 btn btn-primary") }}
                                        <!-- Cancel wont make a post request try doing some research around here -->
                                        <a role="button" href="{{ url_for('main.profile_edit') }}" class="btn btn-warning">Cancel</a>
                                </div>
                        </form>
                </div>
        </div>
        </div>
        </div>
        </div>
        </section>
{% endblock %}

app/templates/profile_edit.html
{% extends "base.html" %}

{% block content %}
<section class="vh-100">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card rounded-3">
          <div class="card-body p-4">

            <div class="col-12 d-flex text-center align-items-center">
              <h4 class="mr-3">To Do App</h4>
              <a role="button" href="{{ url_for('main.profile_add2DoList') }}" data-mdb-button-init data-mdb-ripple-init class="btn btn-warning">Add new task</a>
            </div>

            <table class="table mb-4">
              <thead>
                <tr>
                  <th scope="col">Category</th>
                  <th scope="col">Description</th>
                  <th scope="col">Status</th>
                  <th scope="col">Date Created</th>
                  <th scope="col">Actions</th>
                </tr>
              </thead>
              <tbody>
                {% for todo in todolist %}
                  <tr>
                    <td >{{ todo.category }}</td>
                    <td>{{ todo.description }}</td>
                    <td>{{ todo.status }}</td>
                    <td>{{ todo.created_date.strftime("%b, %d %Y")}}</td>
                    <td>
                      <div class="d-flex">
                        <a href="http://blog-flask-6p7f.onrender.com/profile_edit2DoList/{{ todo.id }}" role="button" class="btn btn-success ms-1 mr-3">Edit</a>
                        <form method="POST">
                          {{ form.csrf_token() }}
                          {{ form.delete_task_id(value='{}'.format(todo.id)) }}
                          {{ form.submit(class="btn btn-danger")}}
                        </form>
                      </div>
                     
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
            <div class="text-center">
                    <a href="{{ url_for('main.profile') }}" method="post" class="btn btn-primary">Return to App</a>
            </div>
          </div>
     
        </div>
        
      </div>
    </div>
  </div>
</section>
{% endblock %}

app/templates/profile_edit2DoList.html
{% extends "base.html" %}

{% block content %}
        <section class="vh-100">
        <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-9 col-xl-7">
                <div class="card rounded-3">
                <div class="card-body p-4">
                        <form class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2" method="POST">
                                {{ form.csrf_token() }}
                                <div class="col-12" style="padding-top: 2em;">
                                        <div data-mdb-input-init class="form-outline mb-4 d-block align-items-center">
                                                {{ form.category.label(class="form-label mr-3") }}
                                                {{ form.category(class="form-control", value=task.category) }}
                                        </div>
                                        <div data-mdb-input-init class="form-outline mb-4 d-block align-items-center">
                                                {{ form.description.label(class="form-label mr-3") }}
                                                <!-- 
                                                        defaultDescription should be "this.innerHTML='{task.description}'"
                                                        but it cannot recognize so I have to use format python to 
                                                        pass in the variable
                                                -->
                                                {{ form.description(class="form-control", onfocus=defaultDescription) }}
                                        </div>
                                        <div data-mdb-input-init class="form-outline mb-4 d-block align-items-center">
                                                {{ form.status.label(class="form-label mr-3") }}
                                                {{ form.status(class="mb-4 d-block align-items-center", default=task.status)}}
                                        </div>
                                       
                                </div>
                                <div class="d-flex flex-row col-12">
                                        {{ form.submit(class="mr-3 btn btn-primary") }}
                                        <!-- Cancel wont make a post request try doing some research around here -->
                                        <a role="button" href="{{ url_for('main.profile_edit') }}" class="btn btn-warning">Cancel</a>
                                </div>
                        </form>
                </div>
        </div>
        </div>
        </div>
        </div>
        </section>
{% endblock %}